# dbt/profiles.yml — used by Airflow inside Docker only
resource_utilization_postgres:
  target: prod
  outputs:
    prod:
      type: postgres
      host: postgres
      port: 5432
      user: mds_user
      password: mds_password
      dbname: btg_resource_utilization
      schema: prod
      threads: 4